### ISSUE TITLE
Confuesd about how does it resolve to use which webpack config file?

### ISSUE THREAD

**Issue by everywill** [iroy2000/react-redux-boilerplate#40]
I look around the project but can not get it out

**Comment by iroy2000** [comment]
@everywill sorry for the late response, I was in vacation

If you look at below file, that is the entry point of the webpack
[webpack.config.babel.js](https://github.com/iroy2000/react-redux-boilerplate/blob/master/webpack.config.babel.js)


And which webpack file to use is based on  your `process.env.NODE_ENV`, you can see more detail at the following file
[shouldBuild.js](https://github.com/iroy2000/react-redux-boilerplate/blob/master/bin/shouldBuild.js)


And the process is also documented here if you want to add different environment 
https://github.com/iroy2000/react-redux-boilerplate#configuration

**Comment by iroy2000** [comment]
@everywill I will close this issue, feel free to reopen if you have other related issues.
