### ISSUE TITLE
Common webpack should load .env when building application for production or release.

### ISSUE THREAD

**Issue by adamjaffeback** [iroy2000/react-redux-boilerplate#46]
Currently, in `webpack.config.common.js`, dotenv only loads if running `npm run dev`. 

https://github.com/iroy2000/react-redux-boilerplate/blob/1729ee8e3643cf14a054b3bbe6e5521d7685f914/webpack.config.common.js#L19-L21

Shouldn't it be just the opposite? Currently, AWS S3 secrets added to the `.env` file will never be loaded for release with webpack-s3-plugin in `webpack.config.prod.js`.

**Comment by iroy2000** [comment]
@adamjaffeback 

Because AWS S3 workflow is optional, so for people who are not using this work flow, I don't want to make `.env` a must have dependency.  

But I will add this  into Q&A in case someone has similar questions.
