### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by ghost** [iroy2000/react-redux-boilerplate#52]
I got the following error while trying to do a basic install:

	Bryans-MacBook-Pro:Documents bryan$ git clone https://github.com/iroy2000/react-redux-boilerplate.git
	Cloning into 'react-redux-boilerplate'...
	remote: Counting objects: 873, done.
	remote: Total 873 (delta 0), reused 0 (delta 0), pack-reused 873
	Receiving objects: 100% (873/873), 556.38 KiB | 1.52 MiB/s, done.
	Resolving deltas: 100% (420/420), done.
	Bryans-MacBook-Pro:Documents bryan$ cd react-redux-boilerplate
	Bryans-MacBook-Pro:react-redux-boilerplate bryan$ npm install
	npm WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
	npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
	npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
	npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
	npm WARN deprecated uws@9.14.0: stop using this version
	npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
	npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
	npm ERR! Unexpected end of JSON input while parsing near '...sign":"^4.1.0","promi'

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/bryan/.npm/_logs/2018-06-16T18_53_57_842Z-debug.log
	Bryans-MacBook-Pro:react-redux-boilerplate bryan$ 

Here is a link to my debug.log: [https://pastebin.com/raw/h4qHUJn5](https://pastebin.com/raw/h4qHUJn5)

**Comment by iroy2000** [comment]
Do you mind telling me your node and npm version ?

**Comment by iroy2000** [comment]
I haven't tried with Node v9+

npm > 5.6.0
node > v8.4.0

I can try v9 a little later and make changes if necessary.  Thanks for reporting that.  If you have already resolved that, feel free to send a PR.

Thanks

**Comment by iroy2000** [comment]
@bgold0 

Can I see your package.json ??

I looked at your pastebin, seems like you have syntax error

![screen shot 2018-06-26 at 2 28 29 pm](https://user-images.githubusercontent.com/487520/41940385-6cc5390c-794d-11e8-8e9e-e87da0656b3f.png)
