### ISSUE TITLE
SyntaxError: Unexpected Identifier when starting

### ISSUE THREAD

**Issue by popey456963** [iroy2000/react-redux-boilerplate#57]
Default instance, cloned about 80 seconds ago.  Ran an `npm i`, then ran the `dev`.  When I try to start it I get the following error:

![](https://femto.pw/96k8.png)

Running node v10.9.0, npm v6.3.0 on Windows 10.

**Comment by iroy2000** [comment]
The problem seems like it cannot understand es6 syntax. 

I haven't tried on window machine, please let us know if you have resolved that, and I can add a section for window user.

**Comment by popey456963** [comment]
Afraid I haven't managed to myself.

**Comment by iroy2000** [comment]
Let me see if I can get a VM and try that.

**Comment by iroy2000** [comment]
Not enough information and inactive thread.  Closing it. Please reopen it if it still existed.
