### ISSUE TITLE
Cached builds

### ISSUE THREAD

**Issue by claweyenuk** [iroy2000/react-redux-boilerplate#58]
Is there any reason why the non-production builds do not use cache loading?  I imagine it would make the builds faster

**Comment by iroy2000** [comment]
Just want to make sure we are on the same page, you are not talking about "cache-loader" that cache expensive loaders ?

https://webpack.js.org/loaders/cache-loader/

Or let me know you mean particular thing ?

**Comment by claweyenuk** [comment]
I am, or hard source webpack loader, or really anything to make builds faster.

As a point of reference, I put 5 minutes into getting hard source webpack loader to work, and it worked find at first, but would periodically start crashing during build, so the default setup will probably require some massaging before it's PR-able

**Comment by iroy2000** [comment]
Thanks for doing that.  It seems a good addition to add disk caching mechanism to boost things up. 

Can you also document your `test case` when you have a PR?  

Thanks a lot

**Comment by iroy2000** [comment]
Inactive thread with no further action. Closing it.
