### ISSUE TITLE
Internalization support

### ISSUE THREAD

**Issue by martino87r** [iroy2000/react-redux-boilerplate#64]
Hi there, excellent starter pack you got there!

Only thing missing seems to be internalization out of the box,
I've settled with react-intl (although alibaba/react-intl-universal looks cool too), and was wondering if it would make sense to add support for it in the starter

**Comment by iroy2000** [comment]
That is a good idea, you want to open a PR on that?  If not, I will take a look and work on it later .

Let me know if you see any features you would like to see as well.

Thanks for your idea!

**Comment by martino87r** [comment]
Honestly I don't feel confident enough to have a PR for such a complex feature :smile: 
In my current project it's working but I don't like they way I structured it... Besides I'm still missing the automatic message generation part

**Comment by iroy2000** [comment]
I found out fb also has a i18n solution came out recently.  Before I go into do the integration, I would like to go reading and compare between them.

**Comment by martino87r** [comment]
I'm testing https://github.com/lingui/js-lingui so far I'm quite OK with it, once I'm sure it works without hiccups I'll create a pull request for integration and short usage demo in the starter.

**Comment by iroy2000** [comment]
Before you look into `js-lingui`, the build is failed on their side.

Also, have you looked into https://facebookincubator.github.io/fbt/docs/api_intro ?

I found out it is more promising in terms of React integration.

**Comment by iroy2000** [comment]
Since there is no update in this thread, I'm going to propose and add https://github.com/yahoo/react-intl

It is widely supported and has an easy to use interface.
