### ISSUE TITLE
Improvement for S3 Deploy

### ISSUE THREAD

**Issue by matthewmorgan** [iroy2000/react-redux-boilerplate#65]
@iroy2000 I ran in to an issue trying to deploy to S3, where is wasn't clear to me from the documentation how to enable the use of the `.env` file for S3 deployment.  in looking at the project history, it seems #46 is related to this.

There's a pattern in deployment workflows that require AWS credentials where they will look for environment variables first, then fall back to an AWS credentials file if those variables are not set.  I can't speak for other developers, but I use Python Boto in my daily work and for this I already have a credentials file in my environment.  Most people using the AWS CLI already have this setup.

It is possible to set our credentials like so:

```javascript
s3Options: {
  credentials: new AWS.SharedIniFileCredentials({profile: process.env.AWS_PROFILE})
},
```

I would propose a few things:

1. `webpack.config.common.js` be changed so that `.env` is loaded there.  This was mentioned in #46.  This makes the values set in `.env` available for all builds, and we could make this safe so that the build does not break if the file is not there.
2. S3 deployments could be conditional on _either_ `config.get('s3.s3Deploy') === 'true'` or an environment variable, EG `S3_DEPLOY=true`.
3. The `.env` file can pick up the user's creds from the credentials file as mentioned above.  The file need only contain three values, for example:

```bash
S3_DEPLOY=true
AWS_PROFILE=default # or whatever profile the user wishes from their ~/.aws/credentials file
AWS_BUCKET=bucketname
```

4. Values in `.env`, if present, would override those set in the credentials profile for users' credentials.  This way, someone could still choose to use `.env` without a credentials file if they chose to do so.
5. The docs would be changed to reflect the above.

If you are amenable to these changes or some variation of them let's figure it out and I will create a PR.  I already have this setup working locally, so it shouldn't be a lot of work for me.

Thanks!

**Comment by iroy2000** [comment]
Sure, let's open a PR! Your proposal makes a lot of sense.

Thanks.
