### ISSUE TITLE
Silence redux devtools warning [PATCH]

### ISSUE THREAD

**Issue by martino87r** [iroy2000/react-redux-boilerplate#67]
The attached patch fixes the redux devtools warning: 
https://github.com/zalmoxisus/redux-devtools-extension/issues/220

[fix_redux_devtools_deprecation.patch.txt](https://github.com/iroy2000/react-redux-boilerplate/files/2746780/fix_redux_devtools_deprecation.patch.txt)

**Comment by iroy2000** [comment]
Ok thanks for that, let me apply the patch tonight! Or feel free to open a PR if you want to.

**Comment by martino87r** [comment]
As funny as it sounds, seems MS screwed up something in the github code and now I'm not able to push to the forked repo:

```
Enter passphrase for key '/home/martino/.ssh/id_rsa': 
ERROR: You must verify your email address.
See https://github.com/settings/emails.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
And yes my email is verified... :man_shrugging:

**Comment by iroy2000** [comment]
lol, you probably need to

**Comment by iroy2000** [comment]
I accidentally push "close"

lol, you probably need to reset up your ssh key ... blah.

**Comment by martino87r** [comment]
Right I forgot to use a different key since I deleted my account some time ago,
and it still says the key is in use... Pull request incoming, along with another one for translation support

**Comment by iroy2000** [comment]
Merged.
