### ISSUE TITLE
Libraries like mdbreact and react-bootstrap do not render their css

### ISSUE THREAD

**Issue by KyleCulp** [iroy2000/react-redux-boilerplate#75]
What is happening is the HTML itself is being rendered, but it's loading it with the default css properties instead of the frameworks. I have tested with mdbreact and react-bootstrap. I'm 99% sure that it is something to do with the webpack settings, but I'm not knowledgeable enough to fix it myself. I've also combed through the github issues for style-loader, css-loader, postcss-loader, and postcss-preset-env but did not find anything matching the current issues I am having. 

Testing I've done:

- Recloned the project, and added mdbreact
- Recloned the project, and added react-bootstrap
- Attempted alias changes with webpack.config.common.js's resolve

**Comment by KyleCulp** [comment]
After much more testing, I figured out that removing sourcemap from postcss-loader & removing the options for css-loader fixed this issue. I cannot say why, if you'd like to chime in on that iroy?

**Comment by iroy2000** [comment]
Sure, I will take a look on that.  Thanks for reporting and documenting the solutions.
